// Layout raíz de la aplicación. Envuelve toda la app con el proveedor de Clerk y aplica la fuente global.
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({
  weight: ['700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "FoodDraft",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}>
        {/* Renderiza el contenido de la app envuelto en ClerkProvider */}
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
